Several Changes & Preventing for exceptions -> Implement Copy to local
DatabaseBuddy/DatabaseBuddy pull request #42
Opened 2021-10-16 12:52 UTC by timi992000

2021-10-18 14:24 UTC, SirCodiac reviewed
!

2021-10-18 14:38 UTC, SirRacoozy requested changes

2021-10-18 14:38 UTC, SirCodiac commented on DatabaseBuddy/View/MainWindow.xaml
> +                                     mah:TextBoxHelper.ClearTextButton="True"
ClearTextButton should only be visible with text within the text box

2021-10-18 14:38 UTC, SirCodiac commented on DatabaseBuddy/ViewModel/MainWindowViewModel.cs
> +        // Using this instead of the "Everyone" string means we work on non-English systems.
Remove useless/nonsense comment

2021-10-19 08:38 UTC, SirCodiac requested changes

2021-10-19 08:38 UTC, SirCodiac commented on DatabaseBuddy.Core/Extender/NumericExtender.cs
> -    public static long ToLongValue(this long? Value)
The ToLongValue with a nullable long is a valid method and should not be removed because this could be needed quite often.

2021-10-19 08:38 UTC, SirCodiac commented on DatabaseBuddy.Core/Extender/NumericExtender.cs
> -    public static double ToDoubleValue(this double? Value)
The ToDoubleValue with a nullable long is a valid method and should not be removed because this could be needed quite often.

2021-10-26 09:09 UTC, SirRacoozy approved these changes

2021-10-26 16:25 UTC, merged